name: Build and Test Docker Image

on:
  push:
    branches:
      - main  # o la rama que uses

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t devops-ping-api .

      - name: Run container to test API response
        run: |
          docker run -d -p 3000:3000 devops-ping-api
          sleep 10
          curl http://localhost:3000/ping
